### Obtener inscripciones
GET http://localhost:3001/api/clases-alumnos
Content-Type: application/json

###

### Inscribir alumno en clase
POST http://localhost:3001/api/clases-alumnos
Content-Type: application/json

{
  "id_alumno": 2,
  "id_clase": 1
}

###

### Actualizar inscripción
PUT http://localhost:3001/api/clases-alumnos
Content-Type: application/json

{
  "id_alumno": 2,
  "id_clase_actual": 1,
  "id_clase_nueva": 3
}

###

### Eliminar inscripción
DELETE http://localhost:3001/api/clases-alumnos
Content-Type: application/json

{
  "id_alumno": 2,
  "id_clase": 3
}

### Obtener alumnos inscriptos a una clase
GET http://localhost:3001/api/clases-alumnos/por-clase/2
Content-Type: application/json

### Obtener clases por fecha
GET http://localhost:3001/api/clases-alumnos/clases-por-fecha?fecha=2025-06-18


### Cambiar contraseña 
PUT http://localhost:3001/api/auth/actualizar-contrasenia
Content-Type: application/json

{
  "dni": "41991329",
  "nueva_contrasenia": ""
}